formatter: "markdown table"

header-from: ./.config/header.md

sections:
  show: 
    - all

content: |-

  {{ .Header}}

  ## Examples with default Network configuration 

   ```hcl

  {{ include "./.config/hclsamples/psql.tf"}}

   ```

    ## Examples with Azure AD admin configuration 

   ```hcl

  {{ include "./.config/hclsamples/psqlwithaadadmin.tf"}}

   ```
    ## Examples with custom DNS and network configuration 

   ```hcl

  {{ include "./.config/hclsamples/psqlcustom.tf"}}

   ```


  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Resources }}

  {{ .Outputs }}

  ## How to update this documentation

  In the module folder, use the following command.

  ```bash

  terraform-docs --config ./.config/.terraform-doc.yml

  ```

output: 
  file: ./readme.md
  mode: replace