formatter: "markdown table"

header-from: ./.config/header.md

sections:
  show: 
    - all

content: |-

  {{ .Header }}

  ## Sample

  Configuration to create a public load balancer.

   ```hcl

  {{ include "./.config/hclsamples/publiclb.hcl"}}

   ```

  Configuration to create an internal load balancer.

   ```hcl

  {{ include "./.config/hclsamples/internallb.hcl"}}

   ```

  Configuration to create an internal gateway load balancer.

   ```hcl

  {{ include "./.config/hclsamples/gateway.hcl"}}

   `

  Configuration to create a public load balancer with diagnostics and alerting enabled.

   ```hcl

  {{ include "./.config/hclsamples/monitoringenabled.hcl"}}

   ```

  Configuration to create a public load balancer Ddos protection.

   ```hcl

  {{ include "./.config/hclsamples/lbwithddosonIp.hcl"}}

   ```


  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Resources }}

  {{ .Outputs }}

  ## How to update this documentation

  In the module folder, use the following command.

  ```bash

  terraform-docs --config ./.config/.terraform-doc.yml .

  ```

output: 
  file: ./readme.md
  mode: replace