formatter: "markdown table"

header-from: ./.config/header.md

sections:
  show: 
    - all

content: |-

  {{ .Header }}

  ## Sample

  Simple usage

   ```hcl

  {{ include "./.config/hclsamples/sample.hcl"}}

   ```


  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Resources }}

  {{ .Outputs }}

  ## How to update this documentation

  In the module folder, use the following command.

  ```bash

  terraform-docs --config ./.config/.terraform-doc.yml .

  ```

output: 
  file: ./readme.md
  mode: replace