formatter: "markdown table"

header-from: ./.config/aks_header.md

sections:
  show: 
    - all

content: |-

  {{ .Header }}

  ## How to call the module

  AKS cluster creation, with diagnostic settings, oms agent and defender specified:

   ```hcl

  {{ include "./.config/hclsamples/aks.tf"}}

   ```


  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Resources }}

  {{ .Outputs }}

  ## How to update this documentation

  In the module folder, use the following command.

  ```bash

  terraform-docs --config ./.config/.terraform-doc.yml .

  ```

output: 
  file: ./readme.md
  mode: replace